spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/api/v1.0}
server.port=${PORT:8080}


aws.access.key=${AWS_ACCESS_KEY_ID:}
aws.secret.key=${AWS_SECRET_ACCESS_KEY:}
aws.region=${AWS_REGION:}
aws.bucket.name=${AWS_BUCKET_NAME:}

jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.hours=${JWT_EXPIRATION_HOURS:10}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

app.upload.base-url=${APP_UPLOAD_BASE_URL}
app.frontend.url=${APP_FRONTEND_URL}